### ISSUE TITLE
[Suggestion] Structure of strategy repository 

### ISSUE THREAD

**Issue by rigwars** [Cryptrality/utilities#1]
Hi folks,

here is some of my suggestion related to Strategy repository to make it easy to maintain and navigate.

**1.** Having a single Repository for all strategy, where any strategy could have his own folder.

**2.** Folder structure would be preferably based on minimum required interval.
E.g.
````
strategies/interval-1m/singleTradepair/MACD-AWESOME/macd-awesome.py
strategies/interval-1m/multiTradepair/MACD-AWESOME-multi/macd-awesome-multi.py
strategies/interval-15m/...
strategies/interval-1h/...
strategies/interval-1d/...
````

**3.** Required + template files.
- The strategy itself in `xyz.py` format
- Readme.dm with:
  - Name of the strategy
  - author (name, donation url, picture etc.)
  - License
  - inspiration/source
  - Backtest / paper trade result from tralirty.com platform (picture or stat result + start - end date)
  - **Disclaimer** (this should be copy/paste) include the information, that these strategies are community distributed, and not guarantee future profit. Use your own risk. + Some legal things.
  
 **4.** Submission rules, every new strategy should be add as a PR request. Before merge it should be verified on trality platform to be able to run as backtest mode.
 
Example of existing similar repositories:

- https://github.com/xFFFFF/Gekko-Strategies
- https://github.com/freqtrade/freqtrade-strategies

**Comment by ffavero** [comment]
I like the second structure best, there are also bots that use multiple periods, I guess it goes down to the smaller period in those cases

**Comment by rigwars** [comment]
> I like the second structure best, there are also bots that use multiple periods, I guess it goes down to the smaller period in those cases

Nice, I removed the first option then.

**Comment by ffavero** [comment]
It would be nice to have a command line option to quickly run a strategy in the terminal and get just the pnl stats. I was thinking to setup a sphinx doc to have some structured content :-P. But time is a bit short

**Comment by rigwars** [comment]
> It would be nice to have a command line option to quickly run a strategy in the terminal and get just the pnl stats. I was thinking to setup a sphinx doc to have some structured content :-P. But time is a bit short

This we could leave as a next step in utilities, I am also thinking that some fast forward local testing tool could be super useful.
